### ISSUE TITLE
文档问题收集

### ISSUE THREAD

**Issue by maxbbn** [tuya/iot-portal#3]
开发文档优化， 请大家反馈下遇到的问题， 接下来会集中优化

**Comment by codeOH** [comment]
对windows系统不友好，项目占用1.6G空间，可能存在依赖项重复等问题

**Comment by ystarlongzi** [comment]
###  1 `./server` 目录名

社区常见的做法是将其用作于
 - 启动本地开发服务（常见于 SPA 架构）
 - 存放 node 端代码（常见于 BFF 架构）

但在这个仓库里，`./server` 是运行在「部署阶段」的，在开发阶段是无关紧要的。和社区的做法有些差异，容易造成理解偏差

建议：移除该目录，将其下的逻辑，通过一个 cli 实现其功能

另外，[./package.json#L9-L11](https://github.com/tuya/iot-portal/blob/master/package.json#L9-L11) 的 script 钩子名称，也建议改为部署、发布相关的命名。比如 `deploy`、`publish` 等


### 2 `./applications` 目录名

如果不能移除 `./server` 目录，建议将该目录名称改为 `./apps` 或 `./client`，感觉这样

 - 更简洁些
 - 降低理解偏差（ `./client` 与 BFF 架构类似）

### 3. 重点区分 mainApp 与 subApp

建议将 `./applications` 目录调整为，强调基座的作用

```
.apps
├── mainApps
├── subApps
│   ├── account-app
│   ├── asset-app
│   ├── ....

```


### 4. 路由自动生成
所有与路由相关的配置，都应该根据 `./applications` 的子目录自动生成。如：

- [/config/nginx.conf](https://github.com/tuya/iot-portal/blob/master/conf/nginx.conf)
- [main-app/src/setupProxy.js](https://github.com/tuya/iot-portal/blob/master/applications/main-app/src/setupProxy.js) 


### 5. 使用 monorepo 管理主应用、子应用？

如题，每个子应用都安装 node_modules，硬盘吃不消 😂  😂

并且，子应用之间也方便共用代码


### 6. 应用启动方式

使用 `npm start` 启动本地开发

提供交互式的方式启动应用，默认启动基座应用，然后再提示选择需要启动的子应用

**Comment by StreakingMan** [comment]
1.准备工作第三步启动http服务，控制台无信息直接exit，有点懵逼
2.文档过于精炼，希望能对一些关键步骤做出解释（这一部目的是啥，内部做了什么工作）
3.调试步骤内容和顺序不太合理，第一二步实际上都属于asset-app的启动过程，第二步中又参杂了第三步中提到的主应用提供的登陆服务...总之第一遍下来，虽然能跑，但理解成本过大
4.建议通过一个简单的场景或项目来引导开发者参与开发流程（比如react教程中的小游戏）

**Comment by maxbbn** [comment]
> 对windows系统不友好

好的， 我们检查下windows 系统的兼容性

**Comment by maxbbn** [comment]
> ### 1 `./server` 目录名
> 社区常见的做法是将其用作于
> 
> * 启动本地开发服务（常见于 SPA 架构）
> * 存放 node 端代码（常见于 BFF 架构）
> 
> 但在这个仓库里，`./server` 是运行在「部署阶段」的，在开发阶段是无关紧要的。和社区的做法有些差异，容易造成理解偏差
> 
> 建议：移除该目录，将其下的逻辑，通过一个 cli 实现其功能
> 
> 另外，[./package.json#L9-L11](https://github.com/tuya/iot-portal/blob/master/package.json#L9-L11) 的 script 钩子名称，也建议改为部署、发布相关的命名。比如 `deploy`、`publish` 等
> 
> ### 2 `./applications` 目录名
> 如果不能移除 `./server` 目录，建议将该目录名称改为 `./apps` 或 `./client`，感觉这样
> 
> * 更简洁些
> * 降低理解偏差（ `./client` 与 BFF 架构类似）
> 
> ### 3. 重点区分 mainApp 与 subApp
> 建议将 `./applications` 目录调整为，强调基座的作用
> 
> ```
> .apps
> ├── mainApps
> ├── subApps
> │   ├── account-app
> │   ├── asset-app
> │   ├── ....
> ```
> 
> ### 4. 路由自动生成
> 所有与路由相关的配置，都应该根据 `./applications` 的子目录自动生成。如：
> 
> * [/config/nginx.conf](https://github.com/tuya/iot-portal/blob/master/conf/nginx.conf)
> * [main-app/src/setupProxy.js](https://github.com/tuya/iot-portal/blob/master/applications/main-app/src/setupProxy.js)
> 
> ### 5. 使用 monorepo 管理主应用、子应用？
> 如题，每个子应用都安装 node_modules，硬盘吃不消 😂 😂
> 
> 并且，子应用之间也方便共用代码
> 
> ### 6. 应用启动方式
> 使用 `npm start` 启动本地开发
> 
> 提供交互式的方式启动应用，默认启动基座应用，然后再提示选择需要启动的子应用
> 
> ### 7. 命令抛错
> [/bin/common.js#L2](https://github.com/tuya/iot-portal/blob/master/bin/common.js#L2) 用法有 node 兼容问题。见[nodejs/node#35740](https://github.com/nodejs/node/issues/35740)
> 
> ### 8. .gitignore 内容不全
> 目前不会忽略 Webstorm 编辑器文件，建议添加以下配置
> 
> ```
> # IDES and editors
> .idea
> 
> # system files
> .DS_Store
> Thumbs.db
> ```
> 
> ### 9. 未配置 lint 钩子

反馈的问题不错， 这个问题建议建一个 issue 讨论
